export const TopBtn=[
    { name:"Home",
     icon:"bi bi-house-fill mx-3"},
     { name:"Shorts",
     icon:"bi bi-file-earmark-play mx-3"},
     { name:"Subscription",
     icon:"bi bi-collection-play mx-3"}

 ]
 export const MinBt=[
    { name:"Home",
     icon:"bi bi-house-fill mx-auto"},
     { name:"Shorts",
     icon:"bi bi-file-earmark-play mx-auto"},
     { name:"Subscription",
     icon:"bi bi-collection-play mx-auto"},
     { name:"Library",
      icon:"bi bi-collection mx-auto"},
      { name:"History",
      icon:"bi bi-clock-history mx-auto"}

 ]
 export const MidBtn=[
     { name:"Library",
      icon:"bi bi-collection mx-3"},
      { name:"History",
      icon:"bi bi-clock-history mx-3"},
      { name:"Your videos",
      icon:"bi bi-play-btn mx-3"},
      { name:"Watch later",
      icon:"bi bi-clock mx-3"},
      { name:"Liked videos",
      icon:"bi bi-hand-thumbs-up mx-3"}

  ]
  export const Explore=[
   { name:"Trending",
    icon:"bi bi-fire mx-3"},
    { name:"Music",
    icon:"bi bi-music-note mx-3"},
    { name:"Movies",
    icon:"bi bi-film mx-3"},
    { name:"Live",
    icon:"bi bi-broadcast mx-3"},
    { name:"Gaming",
    icon:"bi bi-controller mx-3"},
    { name:"News",
    icon:"bi bi-newspaper mx-3"},
    { name:"Sports",
    icon:"bi bi-trophy mx-3"},
    { name:"Learning",
    icon:"bi bi-lightbulb mx-3"},
    { name:"Fashion & Beauty",
    icon:"bi bi-shop-window mx-3"}


]


export const postData = [
    {id:"a",
      url:require("./assets/1.png"),
      name: "Rohit kumar",
      image: require("./assets/ht.jpg"),
      time: "5m",
      dist: "Hey how can i help you in bulding a \"HTML\" website",
      like: "Ravi",
      likeCount:78,
      comment: 15,
      cmt: "can i help you",
      cmtUser: "Sourabh kumar",
      cmtUrl:require("./assets/2.jpg"),
      heart: "1"
    },
    {id:"b",
      name: "Sourabh kumar",
      url:require("./assets/2.jpg"),
      image: require("./assets/cs.jpeg"),
      time: "30m",
      dist: "I can style any html website using \"CSS\"",
      like: "Durgesh",
      likeCount:95,
      comment: 18,
      cmt: "nice post",
      cmtUser: "Rohit kumar",
      cmtUrl:require("./assets/1.png"),
      heart: "1"
    },
    {id:"c",
      url:require("./assets/3.jpg"),
      name: "Prem kumar chandra",
      image: require("./assets/js.png"),
      time: "1h",
      dist: "\"Javascript\" is a magical language for every web developer",
      like: "Sourabh",
      likeCount:175,
      comment: 37,
      cmt: "can i help you",
      cmtUser: "Ravi kumar",
      cmtUrl:require("./assets/5.jpg"),
      heart: "1"
    },
    {id:"d",
      url:require("./assets/4.jpg"),
      name: "Deepak raj",
      image: require("./assets/re.png"),
      time: "6h",
      dist: " \"React\" is a frontend librery of javascript",
      like: "Rohit",
      likeCount:165,
      comment: 31,
      cmt: "nice post",
      cmtUser: "Ayush kumar",
      cmtUrl:require("./assets/6.jpg"),
      heart: "1"
    },
    {id:"e",
      url:require("./assets/5.jpg"),
      name: "Amar prasad",
      image: require("./assets/nd.png"),
      like: "Yuvraj",
      dist:"Node js is the runtime environment",
      likeCount:203,
      comment: 27,
      cmt: "it is js runtime environment",
      cmtUser: "Ankit kumar",
      cmtUrl:require("./assets/4.jpg"),
      time: "1 day"
    },
    {id:"f",
      url:require("./assets/6.jpg"),
      name: "Anurag singh",
      image: require("./assets/ex.png"),
      time: "3 day",
      dist: "\"Express\" is a beckend framework of javascript",
      like: "Harsh",
      likeCount:124,
      comment: 14,
      cmt: "can i help you",
      cmtUser: "Ravi kumar",
      cmtUrl:require("./assets/5.jpg"),
      heart: "1"

    },
    {id:"g",
      url:require("./assets/7.jpg"),
      name: "Rahul kumar",
      image: require("./assets/mo.png"),
      like: "Bikram",
      time: "5 day",
      dist:"MongoDB is a document database used to build scalable internet apps",
      likeCount:96,
      comment: 11,
      cmt: "Ammazing",
      cmtUser: "Mithlesh kumar",
      cmtUrl:require("./assets/8.png"),
      
    },
    {id:"h",
      url:require("./assets/1.png"),
      name: "Rohit kumar",
      image: require("./assets/bt.jpg"),
      time: "1 weak",
      dist: "\"Bootstrap\" helps to make a website mobile resposive",
      like: "Ravi",
      likeCount:143,
      comment: 17,
      cmt: "yes it is helpfull",
      cmtUser: "Sourabh kumar",
      cmtUrl:require("./assets/2.jpg"),
      heart: "1"
    },
    {id:"i",
      url:require("./assets/2.jpg"),
      name: "Sourabh kumar",
      image: require("./assets/c.jpg"),
      time: "1 Weak",
      dist: "C Language is the base for a students programing jurney",
      like: "Durgesh",
      likeCount:237,
      comment: 26,
      cmt: "c is father of all modern programing languages",
      cmtUser: "Rohit kumar",
      cmtUrl:require("./assets/1.png"),
      
    },
    {id:"c",
      url:require("./assets/3.jpg"),
      name: "Prem kumar chandra",
      image: require("./assets/js.png"),
      time: "1h",
      dist: "\"Javascript\" is a magical language for every web developer",
      like: "Sourabh",
      likeCount:175,
      comment: 37,
      cmt: "can i help you",
      cmtUser: "Ravi kumar",
      cmtUrl:require("./assets/5.jpg"),
      heart: "1"
    },
    {id:"d",
      url:require("./assets/4.jpg"),
      name: "Deepak raj",
      image: require("./assets/re.png"),
      time: "6h",
      dist: " \"React\" is a frontend librery of javascript",
      like: "Rohit",
      likeCount:165,
      comment: 31,
      cmt: "nice post",
      cmtUser: "Ayush kumar",
      cmtUrl:require("./assets/6.jpg"),
      heart: "1"
    },
    {id:"e",
      url:require("./assets/5.jpg"),
      name: "Amar prasad",
      image: require("./assets/nd.png"),
      dist:"Node js is the runtime environment",
      like: "Yuvraj",
      likeCount:203,
      comment: 27,
      cmt: "it is js runtime environment",
      cmtUser: "Ankit kumar",
      cmtUrl:require("./assets/4.jpg"),
      time: "1 day"
    }

  ];